# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HUScrollView' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SnapKit'
  pod 'Reveal-iOS-SDK', '~> 1.6.2'
  # Pods for HUScrollView

end
